[package]
name = "rdfpipe-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
oxigraph = "0.3.19"
rio_api = "0.8.4"
rio_turtle = "0.8.4"
